name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Geração da cobrinha 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: MarcellowAugusto
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e Push do SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "gerando animação da cobrinha"
          add: "dist/*.svg"
