name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gerar cobrinha SVG
        uses: Platane/snk@v3
        with:
          github_user_name: MarcellowAugusto
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push da cobrinha
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git status
          git add dist/github-contribution-grid-snake.svg
          git status
          git diff --staged
          git commit -m "Atualizando cobrinha 🐍" || echo "Nada para commitar"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/MarcellowAugusto/MarcellowAugusto.git
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
